"""Add conversation enhancements

Revision ID: a20bc7beec48
Revises: phase3_ai_chatbot
Create Date: 2026-02-08 12:30:30.940668

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a20bc7beec48'
down_revision = 'phase3_ai_chatbot'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('conversation', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('conversation', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('conversation', sa.Column('message_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_conversation_thread_id'), 'conversation', ['thread_id'], unique=True)
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.alter_column('task', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('user', 'theme_preference',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'light'::character varying"))
    op.alter_column('user', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'email'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'email'::character varying"))
    op.alter_column('user', 'theme_preference',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'light'::character varying"))
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('task', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_thread_id'), table_name='conversation')
    op.drop_column('conversation', 'message_count')
    op.drop_column('conversation', 'last_message_at')
    op.drop_column('conversation', 'title')
    op.drop_column('conversation', 'thread_id')
    # ### end Alembic commands ###